package com.paycore.banksim;

import java.util.Optional;

/**
 * What the payments module needs from an acquiring bank. The simulator implements it in-process; a real
 * acquirer client would implement the same interface (HTTP + ISO 8583 semantics hidden behind it).
 * <p>
 * Every call carries a {@code bankRef} generated by the caller BEFORE the call. Banks treat it as an
 * idempotency key, and {@link #lookup(String)} lets the caller ask "did you ever see this?" after a timeout.
 */
public interface BankGateway {

    record CardDetails(String number, int expMonth, int expYear, String cvc) {
        @Override
        public String toString() {
            return "CardDetails[****" + (number == null || number.length() < 4 ? "" : number.substring(number.length() - 4)) + "]";
        }
    }

    record AuthorizeRequest(String bankRef, long amountMinor, String currency, CardDetails card) {
    }

    record RefundRequest(String bankRef, String parentBankRef, long amountMinor, String currency) {
    }

    enum Outcome { APPROVED, DECLINED }

    /** The bank's answer. {@code declineCode} is set only for DECLINED. */
    record BankResponse(Outcome outcome, String declineCode, String authCode, String cardBrand, String cardLast4) {
        public boolean approved() {
            return outcome == Outcome.APPROVED;
        }
    }

    /** The bank's stored view of a transaction, used to resolve timeouts. */
    record BankTransactionStatus(String bankRef, Outcome outcome, String declineCode) {
    }

    BankResponse authorize(AuthorizeRequest request) throws BankTimeoutException;

    BankResponse refund(RefundRequest request) throws BankTimeoutException;

    /** Empty means the bank never received/recorded the request, i.e. it is safe to treat as not happened. */
    Optional<BankTransactionStatus> lookup(String bankRef);
}
