-- Merchants + API keys.
-- IDs are prefixed ULIDs generated by the application (e.g. mer_01J..., key_01J...): time-sortable, URL-safe.

CREATE TABLE merchants (
    id               TEXT PRIMARY KEY,
    name             TEXT        NOT NULL,
    email            TEXT        NOT NULL,
    password_hash    TEXT        NOT NULL,                       -- bcrypt
    fee_bps          INTEGER     NOT NULL DEFAULT 200,           -- 2.00 % gateway fee
    fee_fixed_minor  BIGINT      NOT NULL DEFAULT 300,           -- + 3.00 (minor units) per captured payment
    is_demo          BOOLEAN     NOT NULL DEFAULT FALSE,
    version          INTEGER     NOT NULL DEFAULT 0,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT merchants_email_unique UNIQUE (email),
    CONSTRAINT merchants_fee_bps_range CHECK (fee_bps BETWEEN 0 AND 10000),
    CONSTRAINT merchants_fee_fixed_nonneg CHECK (fee_fixed_minor >= 0)
);

CREATE TABLE api_keys (
    id            TEXT PRIMARY KEY,
    merchant_id   TEXT        NOT NULL REFERENCES merchants (id),
    name          TEXT        NOT NULL,
    prefix        TEXT        NOT NULL,                          -- display only: "sk_test_a1b2c3d4"
    key_hash      TEXT        NOT NULL,                          -- SHA-256(hex) of the full key; plaintext never stored
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    last_used_at  TIMESTAMPTZ,
    revoked_at    TIMESTAMPTZ,
    CONSTRAINT api_keys_hash_unique UNIQUE (key_hash)
);

CREATE INDEX api_keys_merchant_idx ON api_keys (merchant_id);
